defaults:
  permissions:
    - ecm/cms/backend/engine
    - ecm/cms/content_box/index
    - ecm/cms/content_box/show
    - ecm/cms/content_box/new
    - ecm/cms/content_box/create
    - ecm/cms/content_box/edit
    - ecm/cms/content_box/update
    - ecm/cms/content_box/destroy
    - ecm/cms/navigation/index
    - ecm/cms/navigation/show
    - ecm/cms/navigation/new
    - ecm/cms/navigation/create
    - ecm/cms/navigation/edit
    - ecm/cms/navigation/update
    - ecm/cms/navigation/destroy
    - ecm/cms/navigation_item/index
    - ecm/cms/navigation_item/show
    - ecm/cms/navigation_item/new
    - ecm/cms/navigation_item/create
    - ecm/cms/navigation_item/edit
    - ecm/cms/navigation_item/update
    - ecm/cms/navigation_item/destroy
    - ecm/cms/page/index
    - ecm/cms/page/show
    - ecm/cms/page/new
    - ecm/cms/page/create
    - ecm/cms/page/edit
    - ecm/cms/page/update
    - ecm/cms/page/destroy
    - ecm/cms/partial/index
    - ecm/cms/partial/show
    - ecm/cms/partial/new
    - ecm/cms/partial/create
    - ecm/cms/partial/edit
    - ecm/cms/partial/update
    - ecm/cms/partial/destroy
    - ecm/cms/template/index
    - ecm/cms/template/show
    - ecm/cms/template/new
    - ecm/cms/template/create
    - ecm/cms/template/edit
    - ecm/cms/template/update
    - ecm/cms/template/destroy
    - ecm/cms/add_homepages_service/index
    - ecm/cms/add_homepages_service/invoke
    - ecm/cms/add_homepages_service/call
    - ecm/cms/import_partials_service/index
    - ecm/cms/import_partials_service/invoke
    - ecm/cms/import_partials_service/call
  roles:
    ecm/cms/administrator:
      - ecm/cms/backend/engine
      - ecm/cms/content_box/index
      - ecm/cms/content_box/show
      - ecm/cms/content_box/new
      - ecm/cms/content_box/create
      - ecm/cms/content_box/edit
      - ecm/cms/content_box/update
      - ecm/cms/content_box/destroy
      - ecm/cms/navigation/index
      - ecm/cms/navigation/show
      - ecm/cms/navigation/new
      - ecm/cms/navigation/create
      - ecm/cms/navigation/edit
      - ecm/cms/navigation/update
      - ecm/cms/navigation/destroy
      - ecm/cms/navigation_item/index
      - ecm/cms/navigation_item/show
      - ecm/cms/navigation_item/new
      - ecm/cms/navigation_item/create
      - ecm/cms/navigation_item/edit
      - ecm/cms/navigation_item/update
      - ecm/cms/navigation_item/destroy
      - ecm/cms/page/index
      - ecm/cms/page/show
      - ecm/cms/page/new
      - ecm/cms/page/create
      - ecm/cms/page/edit
      - ecm/cms/page/update
      - ecm/cms/page/destroy
      - ecm/cms/partial/index
      - ecm/cms/partial/show
      - ecm/cms/partial/new
      - ecm/cms/partial/create
      - ecm/cms/partial/edit
      - ecm/cms/partial/update
      - ecm/cms/partial/destroy
      - ecm/cms/template/index
      - ecm/cms/template/show
      - ecm/cms/template/new
      - ecm/cms/template/create
      - ecm/cms/template/edit
      - ecm/cms/template/update
      - ecm/cms/template/destroy
      - ecm/cms/add_homepages_service/index
      - ecm/cms/add_homepages_service/invoke
      - ecm/cms/add_homepages_service/call
      - ecm/cms/import_partials_service/index
      - ecm/cms/import_partials_service/invoke
      - ecm/cms/import_partials_service/call
    ecm/cms/reviewer:
      - ecm/cms/backend/engine
      - ecm/cms/content_box/index
      - ecm/cms/content_box/show
      - ecm/cms/navigation/index
      - ecm/cms/navigation/show
      - ecm/cms/navigation_item/index
      - ecm/cms/navigation_item/show
      - ecm/cms/page/index
      - ecm/cms/page/show
      - ecm/cms/partial/index
      - ecm/cms/partial/show
      - ecm/cms/template/index
      - ecm/cms/template/show